name: CCTV News Crawler

on:
  # 定时触发：建议设置为UTC时间，这里北京时间上午8点运行
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点（北京时间8点）运行
  # 手动触发：允许在GitHub网页界面手动运行工作流:cite[2]:cite[6]
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu系统作为运行环境

    steps:
      # 步骤1：拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4  # 官方提供的拉取代码Action

      # 步骤2：设置Python环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # 指定Python版本，与你本地环境保持一致

      # 步骤3：安装Python依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 步骤4：运行爬虫脚本
      - name: Run Crawler
        run: python crawler.py  # 确保此文件名与你的爬虫主脚本文件名一致

      # 步骤5：提交更改（可选但推荐）
      # 此步骤将爬取的新数据和新闻内容自动提交回仓库
      - name: Commit and Push if changed
        run: |
          git config --local user.email "18064625480@163.com"
          git config --local user.name "FireStar0507"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update news data - $(date)"
          git push
